version: "3.8"

networks:
  default:
    name: "camunda_default"

services:
  postgres:
    image: postgres:12-alpine
    hostname: postgres
    environment:
      POSTGRES_USER: "camunda"
      POSTGRES_PASSWORD: "camunda"
      POSTGRES_DB: "process-engine"
    ports:
      - 5432:5432
    networks:
      - default
  
  camunda:
    hostname: camunda
    image: camunda/camunda-bpm-platform:latest
    environment:
      DB_DRIVER: "org.postgresql.Driver"
      DB_URL: "jdbc:postgresql://postgres:5432/process-engine"
      DB_USERNAME: "camunda"
      DB_PASSWORD: "camunda"
    ports:
      - "8080:8080"
    networks:
      - default
